django/pokemon/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('export/', views.ExportView.as_view(), name='export'),
]

django/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokemon.urls'))
]

django/pokemon/models.py
import random
from django.db import models

class Pokemon(models.Model):
    name = models.CharField(max_length=255)
    index = models.PositiveIntegerField()
    sprite_url = models.URLField(max_length=255)
    flavour_texts = models.JSONField()

    # Foreign key relationships to other groups
    types = models.ManyToManyField(
        'pokemon.PokemonType',
    )
    color = models.ForeignKey(
        'pokemon.PokemonColor',
        null=True,
        on_delete=models.SET_NULL
    )
    shape = models.ForeignKey(
        'pokemon.PokemonShape',
        null=True,
        on_delete=models.SET_NULL
    )
    habitat = models.ForeignKey(
        'pokemon.PokemonHabitat',
        null=True,
        on_delete=models.SET_NULL
    )
    egg_groups = models.ManyToManyField(
        'pokemon.PokemonEggGroup',
    )
    evolves_from = models.ForeignKey(
        'pokemon.Pokemon',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='evolves_into'
    )
    # Boolean attribites don't require FK
    is_legendary = models.BooleanField()
    is_mythical = models.BooleanField()

    def __str__(self):
        if self.name.endswith('-f'):
            name = self.name.replace('-f', ' (Female)')
        elif self.name.endswith('-m'):
            name = self.name.replace('-m', ' (Male)')
        else:
            name = self.name
        return name.title()

    @property
    def can_evolve(self):
        return self.evolves_into.all().count() > 0

    def get_sprite_filename(self):
        ext = self.sprite_url.split('/')[-1].split('.')[-1]
        return f'{self.name}.{ext}'

    def random_flavor_text(self):
        return random.choice(self.flavour_texts)

    def get_type_names(self):
        return ", ".join((type.name.title() for type in self.types.all()))

class PokemonType(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)

    def __str__(self):
        return self.name.title()


class PokemonColor(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)

    def __str__(self):
        return self.name.title()


class PokemonShape(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)

    def __str__(self):
        return self.name.title()


class PokemonHabitat(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)

    def __str__(self):
        return self.name.title()


class PokemonEggGroup(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)

    def __str__(self):
        return self.name.title()

django/pokemon/forms.py
from django import forms
from django.conf import settings
from pokemon.models import Pokemon, PokemonType


class PokemonFilterForm(forms.ModelForm):
    can_evolve = forms.BooleanField()
    cant_evolve = forms.BooleanField(label="Can't evolve")

    check_fields = [
        'is_legendary',
        'is_mythical',
        'can_evolve',
        'cant_evolve'
    ]

    class Meta:
        model = Pokemon
        fields = [
            'name',
            'types',
            'color',
            'shape',
            'habitat',
            'egg_groups',
            'is_legendary',
            'is_mythical',
            'can_evolve',
            'cant_evolve'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Removes trailing colon from fieldname
        self.label_suffix = ''

        for field in self.fields:
            self.fields[field].required=False
            if field in self.check_fields:
                # Convenience to include 'true' in URL when checkbox ticked
                self.fields[field].widget.attrs['value'] = 'true'
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'

        # Used to make sure they can't be set at the same time
        self.fields['can_evolve'].widget.attrs['class'] += ' mutually-exclusive'
        self.fields['cant_evolve'].widget.attrs['class'] += ' mutually-exclusive'



class PokemonCreateForm(forms.ModelForm):
    class Meta:
        model = Pokemon
        fields = '__all__'

    def clean_index(self):
        index = self.cleaned_data['index']
        if index > settings.NUMBER_OF_POKEMON:
            raise forms.ValidationError('Invalid index')
        return index

django/pokemon/views.py
import zipfile
import random
import csv

from django.shortcuts import render
from django.views.generic import ListView, View, DetailView
from django.http import JsonResponse, Http404, HttpResponse

from pokemon import forms
from pokemon.models import Pokemon
from pokemon.utils import PokeAPI

class IndexView(ListView):
    ''' Main view for displaying a list of Pokemon and their details '''
    model = Pokemon
    template_name = 'index.html'

    def get_queryset(self):
        qs = super().get_queryset()

        # Filter out by inputs with many-to-many relationships first
        for param in ['types','egg_groups']:
            if param in self.request.GET:
                # Filter by each given item
                values = self.request.GET.getlist(param)
                for value in values:
                    qs = qs.filter(**{param: value})

        # Compile the remaining filters into a set of arguments
        filters = {}
        for param in ['color','shape', 'habitat']:
            value = self.request.GET.get(param)
            if value:
                filters[param] = value

        # Allow searching of names
        if 'name' in self.request.GET:
            filters['name__icontains'] = self.request.GET['name']

        if self.request.GET.get('is_legendary') == 'true':
            filters['is_legendary'] = True

        if self.request.GET.get('is_mythical') == 'true':
            filters['is_mythical'] = True

        if self.request.GET.get('can_evolve') == 'true':
            qs = qs.filter(evolves_into__isnull=False)

        if self.request.GET.get('cant_evolve') == 'true':
            qs = qs.filter(evolves_into__isnull=True)

        return qs.filter(**filters).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(form=forms.PokemonFilterForm(self.request.GET))
        return context


class ExportView(ListView):
    model = Pokemon
    http_method_names = ['post']


    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset()
        return qs.filter(pk__in=self.request.POST.getlist('selected_pokemon'))

    def post(self, request, *args, **kwargs):
        selected_pokemon = self.get_queryset()

        # Export selected pokemon to CSV file
        if 'csv' in self.request.POST:
            return self.generate_csv(selected_pokemon)

        # Download sprites and pack into a zip file
        elif 'sprites' in self.request.POST:
            return self.generate_sprites_zip(selected_pokemon)

        # 404 if anything else submitted
        raise Http404

    def generate_csv(self, queryset):
        response = HttpResponse(
            content_type='text/csv',
            headers={'Content-Disposition': 'attachment; filename="pokemon.csv"'},
        )
        writer = csv.writer(response)
        for pokemon in queryset:
            writer.writerow([
                pokemon.index,
                str(pokemon),
                pokemon.random_flavor_text()
            ])
        return response

    def generate_sprites_zip(self, queryset):
        response = HttpResponse(
            content_type="application/x-zip-compressed",
            headers={'Content-Disposition': 'attachment; filename=sprites.zip'}
        )
        zip_file =  zipfile.ZipFile(
            response,
            mode="w",
            compression=zipfile.ZIP_DEFLATED
        )
        for pokemon in queryset:
            data = PokeAPI.get_sprite(pokemon)
            zip_file.writestr(pokemon.get_sprite_filename(), data)

        zip_file.close()

        return response

django/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.1/highlight.min.js"></script>
  <script src="{% static 'js/pokedex-utils.js' %}"></script>
  <title>Pokedex</title>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex justify-content-center">
  <div class='nav-wrapper'>
    <a class='navbar-brand' href='/'><i class="bi bi-search"></i> Pokedex Search</a>
  </div>

</nav>

<div class="content container-fluid d-flex justify-content-center">
  <div class='wrapper'>
    <div class='row'>
      <div class='col-3'>
        <div class='row filter-form-wrapper'>
          <form method="GET" id='filter-form'>
            {% for field in form.visible_fields %}
              {% if field.name in form.check_fields %}
                <div class='form-check'>
                  {{ field }}
                  {{ field.label_tag }}
                </div>
              {% else %}
                <div class='form-group'>
                  {{ field.label_tag }}
                  {{ field }}
                </div>
              {% endif %}
            {% endfor %}
            <div class='d-flex'>
              <button class='btn btn-primary flex-grow-1 mr-1' type='submit'><i class="bi bi-search"></i> Search</button>
              <button id='btn-reset-filter-form' class='btn btn-danger' type='button'><i class="bi bi-arrow-counterclockwise"></i> Clear</button>
            </div>
          </form>
        </div>
        <div class='row'>
          <button class='btn btn-success btn-block btn-download' type='submit' name='csv' form='pokemon-select-form'>Export to CSV</button>
        </div>
        <div class='row'>
          <button class='btn btn-success btn-block btn-download' type='submit' name='sprites' form='pokemon-select-form'>Download Sprites</button>
        </div>
      </div>

      <div class='col'>
        <table id='tbl-pokemon' class='table table-hover'>

          <thead class='thead-light'>
            <th><input id='checkbox-select-all' type='checkbox'></th>
            <th>Index</th>
            <th>Name</th>
            <th>Types</th>
            <th>Sprite</th>
            <th>Information</th>
          </thead>

        <form id='pokemon-select-form' method="POST" action="{% url 'export' %}">
          {% csrf_token %}
          {% for pokemon in pokemon_list %}
            <tr class='pokemon-row'>
              <td><input value={{ pokemon.pk }} type='checkbox' name='selected_pokemon' class='pokemon-checkbox'></td>
              <td>{{ pokemon.index }}</td>
              <td>{{ pokemon }}</td>
              <td>{{ pokemon.get_type_names }}</td>
              <td><img src="{{ pokemon.sprite_url }}"></td>
              <td class='flavor-text'>{{ pokemon.random_flavor_text }}</td>
            </tr>
          {% empty %}
            <tr><td colspan=6>No results</td></tr>
          {% endfor %}
          </table>
        </form>

      </div>
    </div>
  </div>
</div>

</body>
</html>